### ISSUE TITLE
No longer works with Boost.Test version 1.59

### ISSUE THREAD

**Issue by alarobric** [JetBrains/teamcity-cpp#10]
Boost 1.59 was released mid-August and contains a new version of Boost.Test (finally!). Testing it out today though, it seems this integration with teamcity is broken.

Specifically, teamcity_boost.cpp includes boost/test/unit_test_suite_impl.hpp which no longer exists.

**Comment by shalupov** [comment]
Also review https://github.com/mutanabbi/chewy-cmake-rep/commit/ca7221f916ce631dd14b3be81e2c8d6b4d57659e

**Comment by zaufi** [comment]
Dont' worry, I'll bring that changes as a part of CMake'ification...

**Comment by shalupov** [comment]
Thank you! But I'm really prefer to make changes in small chunks. 
Could you finish cmake'ification and and then Boost.Test 1.59?

Also, should teamcity-cpp support Boost.Test >= 1.59 only or older versions too?

**Comment by zaufi** [comment]
>  I'm really prefer to make changes in small chunks. 
> Could you finish cmake'ification and and then Boost.Test 1.59?

sure! I'm going to finish packaging part of CMake'ification, do rebase and let you know…
Then I'll port 1.59 changes.

> Also, should teamcity-cpp support Boost.Test >= 1.59 only or older versions 

that would be nice, isn't it? it would be easy to implement (i.e. support all versions), so why not to do that?

**Comment by toonetown** [comment]
May I suggest (perhaps) closing this issue, and tracking conversation on PR #14 instead?

**Comment by shalupov** [comment]
Technically PRs in GitHub are shown in the same way as the issues, so it's a good question how it's supposed to be when you have both.

ok, moving to #14

**Comment by toonetown** [comment]
I wish that there were either a way to "merge" an issue into a PR...or to "add" a PR to an issue - but I haven't been able to find a way to do either one of those.  :(

**Comment by toonetown** [comment]
Hey - I actually just found this: https://github.com/blog/1506-closing-issues-via-pull-requests

Maybe I'll resubmit the PR with those keywords and see if it makes it a bit cleaner...
