### ISSUE TITLE
Teamcity does not properly show formatted logs

### ISSUE THREAD

**Issue by pps83** [JetBrains/teamcity-cpp#22]
Here's sample output from teamcity-cpp:

```
##teamcity[testSuiteStarted name='Assert' flowId='1']
##teamcity[testStarted name='AssertionHook' flowId='1']
##teamcity[testFinished name='AssertionHook' duration='0' flowId='1']
##teamcity[testStarted name='AssertInTests' flowId='1']
##teamcity[testFinished name='TeamChat' duration='1171' flowId='3']
##teamcity[testStarted name='WhisperChat' flowId='3']
##teamcity[testStarted name='SlotChain' flowId='2']
##teamcity[testStdOut name='AssertInTests' out='child#7: process started|nchild#7: process exited with ret:201, elapsed time: 33ms' flowId='1']
##teamcity[testFinished name='AssertInTests' duration='38' flowId='1']
##teamcity[testSuiteFinished name='Assert' flowId='1']
```

log:

```
[03:08:32] :		 [Base] Assert
[03:08:32] :			 [Assert] ionHook
[03:08:32] :			 [Assert] InTests
[03:08:32] :				 [InTests] [Test Output]
```

and here's how it looks like on web interface:

![image](https://user-images.githubusercontent.com/1614246/37179566-daf98a3c-22da-11e8-9101-876c228bd059.png)

As you can see, we don't report ionHook or InTest, but AssertionHook and AssertInTests, but somehow TC confuses it.

**Comment by shalupov** [comment]
This is not directly related to teamcity-cpp project, so please file an issue at https://youtrack.jetbrains.com/issues/TW

**Comment by shalupov** [comment]
Also we'll need full output to reproduce it, so please attach it to the issue

**Comment by pps83** [comment]
filled as [TW-54089](https://youtrack.jetbrains.com/issue/TW-54089)

**Comment by pps83** [comment]
Hello Leonid,

can you please update [TW-54089](https://youtrack.jetbrains.com/issue/TW-54089). They asked "What TeamCity version do you use", but I cannot reply there as the page has a blocking request to accept license agreement, which I do not want to read and I cannot accept.

Reply tot that answer is: `TeamCity Enterprise 2017.2.3 (build 51047)`

Thanks.
