### ISSUE TITLE
Format output from similar parallel tests

### ISSUE THREAD

**Issue by pps83** [JetBrains/teamcity-cpp#23]
We use `flowId` with multiple tests running in parallel. Some of these parallel tests run very similar commands with different settings, as a result output that we get in TC is very confusing:

![image](https://user-images.githubusercontent.com/1614246/37182200-0d20f55e-22e5-11e8-8dfe-e5b04a924413.png)

As you can see there are two `Base` test suites and it's not clear which one came from what command. In that screenshot we start 10 test runners in parallel. 2 runners for Base testsuite, for another test suite we start 4 test runners, so the output becomes very confusing if any one of them fails and we need to figure out which one of 4.

So, we run 10 different commands and these are the requirements that we have:
 - for each of the 10 tests running in parallel we want to know what command was used to start it (so that you could easily run that exact cmd to run it again).
 - we run identical test executable with different flavor/environment (let's say Flavor1, and Flavor2). The output should be what flavor used to make that output.
 - test aggregate stats for Base.Atomic shouldn't care if it's Flavor1 or Flavor2.

What formatting should we use to fix the output that TC produces? I can wrap entire output of BaseFlavor1 into its own test suite, but then aggregate test stats will be separate from BaseFlavor2.

Please suggest how to format it properly.
Thanks

**Comment by shalupov** [comment]
This is not directly related to teamcity-cpp project and unfortunately I don't know how to format it properly.
Could you ask at support forum at https://teamcity-support.jetbrains.com/hc/en-us/community/topics/200366709-TeamCity-General-Topics ?

**Comment by pps83** [comment]
First I tried to wrap outputs into `testSuiteStarted`/`testSuiteEnded`, but that affects tests stats aggregation.
Then I changed that to [`blockOpened` / `blockClosed`](https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-blocksBlocksofServiceMessages) and it works for me properly now.
