### ISSUE TITLE
teamcity-cpp/boost/teamcity_boost.cpp needs some changes to compile with boost 1.70.0

### ISSUE THREAD

**Issue by emmett-b** [JetBrains/teamcity-cpp#26]
teamcity-cpp/boost/teamcity_boost.cpp needs something like:

#if BOOST_VERSION >= 107000
    void log_build_info(std::ostream & out, bool) override {
        log_build_info(out);
    }
#endif

inside TeamcityBoostLogFormatter to compile with boost 1.70.0

**Comment by zaufi** [comment]
@emmett-b 
this repo looks abandoned. So, I use my own fork and it's already fixed for boost 1.70 %)

**Comment by emmett-b** [comment]
Hmmm, ok thanks!
Where are we supposed to get updated versions of this?
I guess I should ask JetBrains support...

**Comment by dmitry-treskunov** [comment]
Could you please send us a pull request with the change?

**Comment by zaufi** [comment]
@dmitry-treskunov my repo really differ nowadays from its parent

**Comment by k15tfu** [comment]
@dmitry-treskunov Here it is: https://github.com/JetBrains/teamcity-cpp/pull/27
